//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRotativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotativo
    {
        public int codRot { get; set; }
        public string plaVei { get; set; }
        public System.DateTime datEnt { get; set; }
        public Nullable<System.DateTime> datSai { get; set; }
        public int qtdMin { get; set; }
        public decimal valTotal { get; set; }
    }
}
